/*
This file was generated by Chunky!
You may edit it at your own risk :)
*/
import adminEdit from './components/admin/adminEdit.js';
import adminPagesList from './components/admin/adminPagesList.js';

import elementBox from './components/element/elementBox.js';
import elementButton from './components/element/elementButton.js';
import elementH1 from './components/element/elementH1.js';
import elementH2 from './components/element/elementH2.js';
import elementLink from './components/element/elementLink.js';
import elementList from './components/element/elementList.js';
import elementP from './components/element/elementP.js';
import elementShortcut from './components/element/elementShortcut.js';
import elementSymbol from './components/element/elementSymbol.js';

import interfaceDropdown from './components/interface/interfaceDropdown.js';
import interfaceHeader from './components/interface/interfaceHeader.js';

import miscJson from './components/misc/json.js';

import templateError500 from './components/template/error500.js';
import templatePage from './components/template/page.js';

// here we're listing all the components and
//  re-exporting them all as a global object for easy read by Chunky
export default {
    'admin-edit': adminEdit,
    'admin-pages-list': adminPagesList,
    'element-box': elementBox,
    'element-button': elementButton,
    'element-h1': elementH1,
    'element-h2': elementH2,
    'element-link': elementLink,
    'element-list': elementList,
    'element-p': elementP,
    'element-shortcut': elementShortcut,
    'element-symbol': elementSymbol,
    'interface-dropdown': interfaceDropdown,
    'interface-header': interfaceHeader,
    'misc-json': miscJson,
    'template-error500': templateError500,
    'template-page': templatePage,
}
